config/routes.rb
Eugeneius::Application.routes.draw do

  get "pages/home"
  resources :posts do
  end

  
  root 'pages#home'

    

end

app/models/location.rb
class Location < ActiveRecord::Base


end

app/models/post.rb
class Post < ActiveRecord::Base
	# strong_paramaters :title, :content
	
	validates :title, :content, presence: true
	validates :title, :content, length: {minimum: 2}
	validates :title, uniqueness: true 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

 	def index
 		@posts = Post.all
 	end


 	def show
 		@post = Post.find(params[:id])
 	end

 	def new
 		@post = Post.new

 	end

 	def create
 		@post = Post.new(post_params)

 		if @post.save
 		   redirect_to posts_path, notice: "Cheers! You succefully added a new Spot!"
 		else  
 		   render "new"
 		end  
 	end

 	private

    def post_params
      params.require(:post).permit(:title, :content, :location)
    end


 	def destroy
 		
 	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "TopSpots", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Spots", posts_path %></li>
          <li><%= link_to "Add Spot", new_post_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TopSpots</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<% flash.each do |key, value| %>
	<p><%= value %></p>
<% end %>	

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="center hero-unit" >
  <h1>Welcome to TopSpots</h1>

  <p>Your go to place for the Top Spots in your city!!</p>

  <%= link_to "New York City", posts_path, 
                              class: "btn btn-large btn-primary" %>
  <%= link_to "Chichago", "", 
                              class: "btn btn-large btn-primary" %>
  <%= link_to "San Francisco", "", 
                              class: "btn btn-large btn-primary" %>                    
</div>

app/views/posts/index.html.erb
<h1 class="hero-unit">New York City</h3>
<div class="container">	
<% @posts.each do |post| %>
	<h3>
	  <%= image_tag("photo.jpg", alt: "Spot") %>
	  <%= link_to post.title, post %>
    </h3> 
	<p><%= post.content  %></p>
	<p><%= post.location %></p>
	<hr />
<% end %>	
</div>

app/views/posts/new.html.erb
<div class="container hero-unit">
   <h1>Add a New Spot</h1>
    <%= form_for @post do |f| %>
      <% if @post.errors.any? %>
        <h2>Errors</h2>
          <ul>
            <%= @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>  
          </ul> 
       <% end %> 
       <p>
         <%= f.label :location, "City" %>
         <br>
         <%= f.text_field :location %>
       </p> 
       <p>
         <%= f.label :title, "Spot Name" %>
         <br>
         <%= f.text_field :title %>
       </p>
       <p>
         <%= f.label :content, "Description" %>
         <br>
         <%= f.text_area :content %>
       </p>
       <p><%= f.submit "Add new Spot" %></p>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="container hero-unit">
<h1><%= @post.title %></h1>
<p class="center"><%= @post.location  %></p>
<h3><%= @post.content %> </h3>
</div>

<div class="container">
<%= image_tag("spot1.jpg", alt: "Spot") %> 
<%= image_tag("spot3.jpg", alt: "Spot") %> 
<%= image_tag("spot5.jpg", alt: "Spot") %> 
</div>